- realm/chess.gno
- realm/rules.gno
- realm/rules_test.gno
engine now passes perft tests (tested using the go version, as gnovm's too slow for an efficient testing feedback loop)
> feat(engine): en passant, complete castling, move generator, perft

- web/layouts/dashboard/section.html
- web/public/about/index.html
- web/public/dashboard/index.html
- web/public/index.html
- web/public/play/index.html
- web/public/terms/index.html
Fix: dashboard tiles responsive grid
> fix: dashboard responsive

- realm/chess.gno
- realm/chess_test.gno
- realm/time.gno
> feat(realm): add time controls, better testing

- web/assets/js/actions.ts
- web/assets/js/components/dashboard.ts
- web/layouts/dashboard/section.html
Update UI to use Player data instead of partitioned rating.
> refactor: dashbard rating & position

- web/assets/css/main.css
- web/assets/js/components/dashboard.ts
- web/layouts/partials/header/header.html
> chore: fix typos

- web/assets/js/actions.ts
- web/assets/js/types/errors.ts
- web/assets/js/utils/errors.ts
This PR introduces fine-grained faucet error handling
> feat: add faucet error handling

- .gitignore
- Makefile
> chore: create Makefile for local dev

- signup/src/shared/schemas/formSchema.ts
This PR corrects the signup form validation message for the email field
> fix: correct email validation message

- .gitignore
- web/layouts/partials/head/favicons.html
- web/vite.config.js
- web/vite.config.server.js
Cleans up console
Adds sourcemaps
> feat: Let's make our lives easier for now

- realm/chess.gno
Uploading this trying to fix #49
> Close timed-out games

- web/assets/js/components/gameboard.ts
> fix: selectCell implicit return should be called before promise

- tutorial/01_getting_started/README.md
Adding more information and small improvement in [tutorial/01_getting_started/README.md](tutorial/01_getting_started/README.md)
> chore: update README.md

- web/assets/js/actions.ts
- web/assets/js/components/gameoptions.ts
- web/assets/js/components/gameplayers.ts
- web/assets/js/types/types.ts
This PR fixes the game timer rendering from `NaN` to actual values
> fix: correct game timer rendering

- realm/chess.gno
- realm/chess_test.gno
- realm/discovery.gno
- realm/lobby.gno
- realm/lobby_test.gno
> fix: lobby refactor, more commandTests, add tests to lobby

- web/assets/js/actions.ts
- web/assets/js/components/gameboard.ts
This PR parses rival moves correctly and enables the game to be played. It also tweaks the `rivalMove` method to be cleaner
> fix: parse rival moves correctly

- Makefile
> chore: add additional tokens for bigger testing sessions

- .github/workflows/realm.yml
> ci: set up realm testing on CI

- Makefile
- realm/chess.gno
- realm/chess_test.gno
- realm/discovery.gno
- realm/util.gno
> chore: go improvements

- signup/functions/subscribe.ts
- signup/functions/types.ts
- signup/src/components/pages/Home/Home.tsx
This PR adds the Privacy Policy to the signup form. Adds in missing type imports for Netlify functions.
> fix: improve form

- Makefile
- web/assets/js/components/gameboard.ts
> fix: display captured pieces

- web/assets/js/actions.ts
cc/ @moul 
just a small aid in debugging :)
> feat(web): gnokey logs in console.info

- realm/lobby.gno
- realm/rules.gno
Fixes #97. Tested using the process outlined in my comment.
> fix: re-instantiate Board on NewBoard

- web/assets/js/actions.ts
substitute for Antonio's pr #118.
(I don't know about the WS changes, it's prettier who's doing them and I don't know why it's giving different results)
> fix: handle NotInLobby error

- realm/discovery.gno
> fix: get Player as a pointer

- web/assets/js/components/gameboard.ts
- web/assets/js/components/gameplayers.ts
Related to https://github.com/gnolang/gnochess/issues/115
> Fix: timeout

- .github/workflows/integration.yml
- Makefile
- go.mod
- go.sum
- integration_test.go
- testdata/addpkg.txtar
- testdata/addpkg_gnochess.txtar
- testdata/basic_commands.txtar
add base integration test system using embed gnoland node with txtar:
> feat: add integration tests

- web/assets/js/actions.ts
- web/package-lock.json
- web/package.json
This PR returns the WSProvider after the client JS libraries have been properly updated
> fix: return ws provider

- web/assets/js/routes/home.ts
- web/layouts/index.html
- web/layouts/partials/canvas/canvas.html
- web/layouts/partials/gui/banner.html
style: fix white timer style ✅
> style: fix responsive white timer

- tutorial/02_move_validator/rules.gno
Add TODO to the top level function to make it easier to find and match to the README instructions
> chore: update rules.gno for easier UX

- Makefile
```console
$ make z_poormans_dashboard
g1tdnv6wzylf5fdex30d8qrf6f32frvulsjpr63z 1 0
g1j8ynm8wtepgavmumz6mqdwwdz497cgxm3q4u28 1 0
g1fj4f8l0cvnrr4kezg7peehl0w443pelg4l6jgh 1 0
g1hu8ljfp9jy9mjqk40kp4czquxgm6d20pyd2qnh 1 0
g1q7qrpknm2j4p2alzwrm4exusn0mu42a5csgl7w 1 0
g1lk0dxctssev0qk38s3srwdsxyzan05w56m8su3 2 0
g1q897pse9ydnqemdzj2jcdkhyvmy69rnym47rjs 1 0
g15q7jvxuwj9g6z28rjvta8szpy59rwr2j4u4s35 1 0
g1kg9rap8pwq4hm0vcvnce7h0t83v6eyvlxw3rzh 1 0
```
> chore: add 'make z_poormans_dashboard'

- realm/chess.gno
- realm/gno.mod
- tutorial/03_playing_together/chess.gno
> chore: remove unused import "ufmt"

- .github/workflows/deploy-realm.yml
Small fix in the deployment workflow to make use of environment variables
> fix(ci): Useless env var removed and useful one used
